sudo: required
services:
  - docker
before_install :
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END AND BEFORE RAKE START"
  - rake spec
  - echo "BEFORE INSTALL END"
  - docker build -t sivamsis/docker-react -f Dockerfile.dev .

scriipt:
  - docker run sivamsis/docker-react npm run test -- -- coverage

